name: Deploy to Raspberry Pi

on:
  push:
    branches:
      - master # Zmień na swoją odpowiednią gałąź

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Test SSH connection
        env:
          HOST: ${{ secrets.RPI_HOST }}
          USER: ${{ secrets.RPI_USER }}
          KEY: ${{ secrets.RPI_SSH_KEY }} # Klucz SSH jako string
        run: |
          echo "Attempting to connect to $USER@$HOST"
          echo "$KEY" > /tmp/id_rsa
          chmod 600 /tmp/id_rsa
          ssh -i /tmp/id_rsa -o StrictHostKeyChecking=no $USER@$HOST "echo Connection successful" || exit 1

      - name: Deploy to Raspberry Pi
        env:
          HOST: ${{ secrets.RPI_HOST }}
          USER: ${{ secrets.RPI_USER }}
          KEY: ${{ secrets.RPI_SSH_KEY }}
        run: |
          echo "$KEY" > /tmp/id_rsa
          chmod 600 /tmp/id_rsa
          ssh -i /tmp/id_rsa -o StrictHostKeyChecking=no $USER@$HOST 'cd /app/Backend && git pull origin master && npm install && pm2 restart backend'
