name: CI/CD for Expo React Native Backend
on:
  push:
    branches:
      - master  # Upewnij się, że używasz właściwej gałęzi

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: List files in working directory
        run: |
          pwd
          ls -al

      - name: Install dependencies
        run: |
          cd Backend  # Zmień to, jeśli Twój plik package.json znajduje się w innym katalogu
          npm install

      - name: Build the project
        run: |
          cd Backend  # Znowu upewnij się, że jesteś w odpowiednim katalogu
          npm run build

      - name: Deploy to Raspberry Pi
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.RPI_HOST }}
          username: ${{ secrets.RPI_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            echo "Deploying to Raspberry Pi ${host} as ${username} using key ${key}"
            cd /app/Backend  # Ścieżka na Raspberry Pi do katalogu backendu
            git pull origin master  # Pobranie ostatnich zmian
            npm install  # Instalacja zależności
            npm run start  # Uruchomienie aplikacji
