name: CI Pipeline

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      # Krok 1: Checkout kodu z repozytorium
      - name: Checkout code
        uses: actions/checkout@v2

      # Krok 2: Instalacja Node.js w wersji 20.9.0
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.9.0' # Ustaw wersję Node.js
      # Krok 3: Przejdź do folderu Backend
      - name: Change directory to Backend
        run: cd Backend 
      
      - name: Pull 
        run: git pull origin master
      # Krok 4: Instalacja zależności projektu
      - name: Install dependencies
        run: |
          cd Backend # Upewnij się, że jesteśmy w folderze Backend
          npm install

      # Krok 5: Budowanie projektu
      - name: Run build
        run: |
          cd Backend # Upewnij się, że jesteśmy w folderze Backend
          npm run build
      # Krok 5: Restart serwera (np. PM2)
      - name: Restart server
        run: |
          pm2 stop all || true  # Zatrzymaj wszystkie instancje aplikacji
          pm2 restart index || pm2 start npm --name "index" -- run start # Restartuj lub uruchom aplikację, jeśli nie istnieje
