name: Deploy to Raspberry Pi

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to Raspberry Pi
      env:
        HOST: ${{ secrets.RPI_HOST }}
        USER: ${{ secrets.RPI_USER }}
        KEY: ${{ secrets.RPI_SSH_KEY }}
      run: |
        ssh -i $KEY $USER@$HOST 'cd /home/admin/app && git pull origin main && npm install && pm2 restart app'
