on: 
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Debug SSH Setup
      run: |
       ls -la ~/.ssh  # Sprawdź, jakie pliki są w .ssh
       cat ~/.ssh/id_rsa  # Wyświetl klucz (upewnij się, że nie jest to na produkcji)
       cat ~/.ssh/known_hosts  # Sprawdź znane hosty

    - name: Debugging SSH Setup
      run: |
        pwd  # Pokaż aktualny katalog roboczy
        ls -la  # Sprawdź zawartość katalogu
        mkdir -p ~/.ssh
        ls -la ~/.ssh  # Sprawdź, czy katalog został utworzony
        echo "${{ secrets.SSH_PRIVATE_KEY }}" | tr -d '\r' | ssh-add -
        ssh-keyscan -H ${{ secrets.RASPBERRY_PI_IP }} >> ~/.ssh/known_hosts
        cat ~/.ssh/known_hosts  # Sprawdź, czy host został dodany
        

    - name: Setup SSH
      run: |
        set -x
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" | tr -d '\r' | ssh-add -
        ssh-keyscan -H ${{ secrets.RASPBERRY_PI_IP }} >> ~/.ssh/known_hosts

    - name: Deploy to Raspberry Pi
      run: ssh ${{ secrets.SSH_USER }}@${{ secrets.RASPBERRY_PI_IP }} "command_to_run"
      env:
        SSH_AUTH_SOCK: /tmp/ssh_agent.sock