name: CI/CD for Expo React Native Backend
on:
  push:
    branches:
      - master  # Wybierz główną gałąź, np. main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          npm install

      - name: Build the project
        run: |
          npm run build

      - name: Deploy to Raspberry Pi
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.RPI_HOSTHOST }}  # IP Twojego Raspberry Pi
          username: ${{ secrets.RPI_USER }}  # Nazwa użytkownika na Pi
          password: ${{ secrets.RPI_PASSWORD }}  # Hasło lub możesz użyć kluczy SSH
          port: 22
          script: |
            cd /app/Backend  # Ścieżka do backendu na Raspberry Pi
            git pull origin master  # Pobierz ostatnie zmiany
            npm install  # Zainstaluj zależności
            npm run start  # Uruchom aplikację
