name: Deploy to Raspberry Pi

on:
  push:
    branches:
      - master  # lub inna główna gałąź

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Copy files to Raspberry Pi
      run: |
        scp -r ./ admin@192.168.8.162:/home/admin/testapp

    - name: Restart PM2 service
      run: |
        ssh admin@192.168.8.162 'pm2 restart all'
