name: CI Pipeline

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.9.0'

      - name: Install dependencies
        run: |
          echo "Instalowanie zależności..."
          cd ~/app/Backend
          npm install
          echo "Zależności zainstalowane."

      - name: Pull latest changes
        run: |
          echo "Pobieranie najnowszych zmian..."
          cd ~/app/Backend
          git pull origin master
          echo "Najnowsze zmiany pobrane."

      - name: Restart PM2 application
        run: |
          echo "Restartowanie aplikacji PM2..."
          pm2 stop backend || true
          pm2 start ~/app/Backend/index.ts --name "backend" --interpreter bun
          echo "Aplikacja PM2 została zrestartowana."

      - name: Show PM2 status
        run: |
          echo "Aktualny status PM2:"
          pm2 status
