name: Deploy to Raspberry Pi

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Debug SSH Key
      run: |
        echo "${{ secrets.RASPBERRY_PI_SSH_KEY }}" | base64 -d > /tmp/ssh_key
        chmod 600 /tmp/ssh_key
        ls -l /tmp/ssh_key

    - name: Copy files to Raspberry Pi
      run: |
        scp -i /tmp/ssh_key -r ./* ${{ secrets.RASPBERRY_PI_USER }}@${{ secrets.RASPBERRY_PI_IP }}:/home/admin/app/Backend
      shell: /usr/bin/bash -e {0}