name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # lub inna wersja Node.js

      - name: Install dependencies for backend
        working-directory: ./Backend
        run: npm install

      - name: Install dependencies for frontend
        working-directory: ./Frontend
        run: npm install

      - name: Deploy to Raspberry Pi
        run: |
          ssh -o StrictHostKeyChecking=no -i ${{ secrets.SSH_KEY }} admin@192.168.8.162 'bash -s' < ./scripts/deploy.sh
