name: Deploy to Raspberry Pi

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to Raspberry Pi
        env:
          HOST: ${{ secrets.RPI_HOST }}
          USER: ${{ secrets.RPI_USER }}
          KEY: ${{ secrets.RPI_SSH_KEY }}
        run: |
          ssh -i $KEY $USER@$HOST '
          cd /app/Backend || exit 1
          git reset --hard HEAD
          git clean -fd
          git pull origin main || exit 1
          npm install || exit 1
          pm2 restart backend || exit 1'
