name: Test SSH Connection to Raspberry Pi

on:
  push:
    branches:
      - master

jobs:
  test-ssh-connection:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Debug SSH connections
      env:
        PI_HOST: ${{ secrets.RPI_HOST }}
        PI_USER: ${{ secrets.RPI_USER }}
        SSH_PRIVATE_KEY: ${{ secrets.SSH_KEY }}
      run: |
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan $PI_HOST >> ~/.ssh/known_hosts
        echo "SSH key setup complete"
        ls -la ~/.ssh
        cat ~/.ssh/id_rsa
        ssh -v -i ~/.ssh/id_rsa $PI_USER@$PI_HOST echo "SSH connection successful"
      shell: /usr/bin/bash -e {0}