name: CI Pipeline

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.9.0'

      - name: Install dependencies
        run: |
          cd ~/app/Backend
          npm install

      - name: Pull latest changes
        run: |
          cd ~/app/Backend
          git pull origin master

      - name: Restart PM2 application
        run: |
          pm2 stop backend || true
          pm2 start index.ts --name "backend"
