name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # lub inna wersja Node.js

      - name: Deploy to Raspberry Pi
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > id_rsa
          chmod 600 id_rsa
          ssh -o StrictHostKeyChecking=no -i id_rsa admin@46.112.108.11 'bash -s' < ./scripts/deploy.sh
          rm id_rsa  # opcjonalnie, aby usunąć klucz po użyciu