name: Deploy to Raspberry Pi

on:
  push:
    branches:
      - master  # Zmień na odpowiednią nazwę gałęzi

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create SSH key
        run: |
          echo "${{ secrets.RPI_SSH_KEY }}" > /tmp/id_rsa
          chmod 600 /tmp/id_rsa

      - name: Test SSH connection
        env:
          HOST: ${{ secrets.RPI_HOST }}
          USER: ${{ secrets.RPI_USER }}
        run: |
          echo "Testing SSH connection..."
          ssh -i /tmp/id_rsa $USER@$HOST "echo Connection successful" || exit 1

      - name: Deploy to Raspberry Pi
        env:
          HOST: ${{ secrets.RPI_HOST }}
          USER: ${{ secrets.RPI_USER }}
        run: |
          ssh -i /tmp/id_rsa $USER@$HOST '
          if [ ! -d "/app/Backend/.git" ]; then
            echo "Cloning the repository..."
            git clone https://github.com/user/repo.git /app/Backend || exit 1
          fi
          echo "Changing directory to Backend..."
          cd /app/Backend || exit 1
          echo "Resetting repository..."
          git reset --hard HEAD || exit 1
          git clean -fd || exit 1
          echo "Pulling latest changes..."
          git pull origin master -v || exit 1  # Zmień na odpowiednią nazwę gałęzi
          echo "Installing dependencies..."
          npm install || exit 1
          echo "Restarting PM2..."
          pm2 restart backend || exit 1
          echo "Deployment completed successfully!"
          '
