name: CI/CD for Expo React Native Backend
on:
  push:
    branches:
      - master 

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          cd Backend  # Change this to the correct directory if needed
          npm install

      - name: Build the project
        run: |
          cd Backend  # Change this to the correct directory if needed
          npm run build
      - name: Debug SSH Connection
        run: |
          ssh -v ${{ secrets.RPI_USER }}@${{ secrets.RPI_HOST }} 'echo "SSH connection successful"'
        env:
          RPI_HOST: ${{ secrets.RPI_HOST }}
          RPI_USER: ${{ secrets.RPI_USER }}
          SSH_KEY: ${{ secrets.SSH_KEY }}