name: Deploy to Raspberry Pi

on:
  push:
    branches:
      - master  # Zmien na swoja glowna gałąź, jeśli używasz innej

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Test SSH connection
        env:
          HOST: ${{ secrets.RPI_HOST }}
          USER: ${{ secrets.RPI_USER }}
          KEY: ${{ secrets.RPI_SSH_KEY }}
        run: |
          echo "$KEY" > key.pem
          ssh -i <(echo "$KEY") -o StrictHostKeyChecking=no $USER@$HOST "echo Connection successful" || exit 1

      - name: Deploy to Raspberry Pi
        env:
          HOST: ${{ secrets.RPI_HOST }}
          USER: ${{ secrets.RPI_USER }}
          KEY: ${{ secrets.RPI_SSH_KEY }}
        run: |
          ssh -i <(echo "$KEY") -o StrictHostKeyChecking=no $USER@$HOST 'cd /path/to/your/app && git pull origin master && npm install && pm2 restart backend'
