on: 
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup SSH
      run: |
        set -x
        echo "Tworzenie katalogu a .ssh"
        mkdir -p ~/.ssh
        echo "Zawartość katalogu przed dodaniem klucza:"
        ls -la ~/.ssh || echo "Katalog ~/.ssh nie istnieje."
        echo "${{ secrets.SSH_PRIVATE_KEY }}" | tr -d '\r' > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        eval "$(ssh-agent -s)"
        ssh-add ~/.ssh/id_rsa
        echo "Zawartość katalogu po dodaniu klucza:"
        ls -la ~/.ssh

        # Dodajemy znane hosty
        echo "Dodawanie znanych hostów:"
        ssh-keyscan -H ${{ secrets.RASPBERRY_PI_IP }} >> ~/.ssh/known_hosts || echo "Błąd podczas dodawania znanych hostów"

        echo "Zawartość pliku id_rsa:"
        cat ~/.ssh/id_rsa
        echo "Zawartość pliku known_hosts:"
        cat ~/.ssh/known_hosts

    - name: Deploy to Raspberry Pi
      run: |
        echo "Próba połączenia SSH"
        ssh -i ~/.ssh/id_rsa ${{ secrets.SSH_USER }}@${{ secrets.RASPBERRY_PI_IP }} "echo 'Połączenie udane!'" || echo "Błąd przy próbie połączenia SSH"
        ssh ${{ secrets.SSH_USER }}@${{ secrets.RASPBERRY_PI_IP }} "command_to_run"