name: CI Pipeline

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      # Krok 1: Checkout kodu z repozytorium
      - name: Checkout code
        uses: actions/checkout@v2

      # Krok 2: Instalacja Node.js w wersji 20.9.0
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.9.0' # Ustaw wersję Node.js

      # Krok 3: Instalacja zależności
      - name: Install dependencies
        run: |
          cd app/Backend  # Przejdź do folderu Backend
          npm install

      # Krok 4: Budowanie projektu (jeśli jest wymagane)
      - name: Run build
        run: |
          cd app/Backend  # Przejdź do folderu Backend
          npm run build   # Wykonaj budowanie projektu, jeśli jest

      # Krok 5: Restart serwera (np. PM2)
      - name: Restart server
        run: |
          cd app/Backend  # Przejdź do folderu Backend
          pm2 stop backend || true  # Zatrzymaj aplikację, jeśli działa
          pm2 start index.ts --name "backend"  # Uruchom aplikację

